[package]
name = "drewno_mars"
version = "0.1.0"
edition = "2021"

[dependencies]
lalrpop-util = { version = "0.20.0", features = ["lexer", "unicode"] }
logos = "0.13.0"
indoc = "2"

[build-dependencies]
lalrpop = "0.20.0"

[dev-dependencies]
assert_cmd = "2.0.12"