[package]
name = "drewno_mars"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.13.0"

# Example of customizing binaries in Cargo.toml.
# [[bin]]
# name = "dmc"
# path = "src/main.rs" 
